all: print_nums                      

print_nums: PrintNums.cpp           
	g++ -o print_nums PrintNums.cpp

PrintNums.o: PrintNums.cpp           
	g++ -c PrintNums.cpp

clean:                                 
	rm *o print_nums
